#!/usr/bin/env bash

# script installs nginx in an ubuntu web server and configures its virtualhost

# updates packages
# sudo apt-get update
sudo apt-get install nginx -y

# nginx server block configuration to serve on localhost(till domain is used...)
# but first, copy original configuration elsewhere if you screw things up

sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default_copy

echo 'server {
     listen 80 default_server;
     listen [::]:80 default_server;

     root /var/www/html;
     index index.html;
     
     location / {
     	      return 200 "Hello World!";
	      }
}' | sudo tee /etc/nginx/sites-available/default > /dev/null

# restart nginx without systemctl. systemctl for RHEL-based repos not using VMs
sudo service nginx restart
