#!/usr/bin/env bash
# script installs nginx in an ubuntu web server and configures its virtualhost

# proper guide here: https://www.digitalocean.com/community/tutorials/how-to-install-nginx-on-ubuntu-22-04

# updates packages
sudo apt-get update -y

# installs nginx and deps/packages needed
sudo apt-get install nginx -y

# it is enabled by default if installed, but still nice to doubleconfirm...
sudo ufw allow 'Nginx HTTP'

# create html file first
echo 'Hello World!' > index.html

# move to the www/html directory
sudo mv index.html  /var/www/html

# restart nginx (ubuntu vm)
sudo service nginx restart
