#!/usr/bin/env bash
# script installs nginx in an ubuntu web server and configures its virtualhost

# proper guide here: https://www.digitalocean.com/community/tutorials/how-to-install-nginx-on-ubuntu-22-04

# updates packages
sudo apt-get update -y

# installs nginx and deps/packages needed
sudo apt-get install nginx -y

# it is enabled by default if installed, but still nice to doubleconfirm...
sudo ufw allow 'Nginx HTTP'

# create html file first
echo 'Hello World!' > index.html

# create error page file
echo "Ceci n'est pas une page." > 404.html

# move to the www/html directory
sudo mv index.html  /var/www/html

# move 404.html file to www/html
sudo mv 404.html /var/www/html/

# redirect url
REDIRECT_URL="https://github.com/meistens"

# using sed to write multiple lines
sudo sed -i "/listen \[::\]:80 default_server;/a \
\
	location /redirect_me {\
		 return 301 $REDIRECT_URL;\
		 }" /etc/nginx/sites-available/default

# write 404 directive using sed
sudo sed -i "/server_name _; /a\\\terror_page 404 /404.html;" /etc/nginx/sites-available/default

# restart nginx (ubuntu vm)
sudo service nginx restart
