#!/usr/bin/env bash
# script checks nginx status and allows allconnections to listen on port 80
sudo service nginx start
sudo sed -i "s/8080/80/g" /etc/nginx/sites-enabled/default
sudo service nginx restart
