#!/usr/bin/env bash
#Script prints "Best School", "good luck" on 4th loop, "bad luck" on 8th loop
i=1
while [ $i -le 10 ]
do
    if [ $i -eq 4 ]
    then
	echo "bad luck"
    elif [ $i -eq 8 ]
    then
	echo "good luck"
    else
	echo "Best School"
    fi
    i=$((i+1))
done
