#!/usr/bin/env bash
#displays the current directory, without displaying hidden files
for file in *
do
    if [[ "$file" != ".*" ]]
    then
	if [[ "$file" = *"-"* ]]
	then
	    echo "${file##*-}"
	else
	    echo "$file"
	fi
    fi
done
